name : another ci
on: push

jobs:
  lint:
    name : Lint Code
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name : Install dependencies
        run: npm install

      - name : Run lint
        run: npm run lint

  build:
    name : Build
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name : Install dependencies
        run: npm ci

      - name : Build project
        run: npm run build
  
  test:
    name : Test
    needs : [lint,build]
    runs-on: ubuntu-latest
      
    steps:
      - name : Checkout code
        uses: actions/checkout@v4
      
      - name : Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name : Install dependencies
        run: npm install
      
      - name : Run tests
        run: npm test

  deploy:
    name : Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name : Install dependencies
        run: npm install

      - name : Deploy
        run: npm run deploy

